/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    EventForm: typeof import('./src/components/TheCalendarView/EventForm.vue')['default']
    Home: typeof import('./src/components/IndexView/Home.vue')['default']
    LoginPanel: typeof import('./src/components/LoginPanel/LoginPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCalendarFull: typeof import('./src/components/TheCalendarView/TheCalendarFull.vue')['default']
  }
}
